[variables]
var_decl = "noob"
var_assign = ["is", "is a"]

[function]
func_decl = ["diy", "DIY"]
func_parameter_seperator = [":", "with"]
func_return = "yeet"

[conditions]
cond_if = "Q:"
cond_if2 = "A:"
cond_brackets_open = ':\)'
cond_brackets_close = ':\('
cond_while = "fruitloop"
cond_for = "4"

[logical_operators]
not = "not the"
and = "and"
or = "or"

[arithmetic_operators]
addition = "w/"
subtraction = "w/o"
multiplication = "x"
division = "/"
modulo = "rest"

[comparison_operators]
greater_than = '^'
greater_equal = '^€'
equal = "€"
less_equal = "v€"
less_than = "v"

[special_functions]
spec_output = ["lol", "LOL"]
spec_input = "gimme"
spec_open = "open"
spec_close = ["Fuck off", "FUCK OFF"]
